# Generated by Django 4.2.5 on 2023-09-27 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='pecepie_desc',
            new_name='recipe_desc',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='Recepie_name',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='receipes',
            name='recipe_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipe'),
        ),
    ]
