# Generated by Django 4.2.5 on 2023-10-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegi', '0002_rename_pecepie_desc_receipes_recipe_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
