# Generated by Django 4.2.5 on 2023-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0006_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_cardcreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
